config/routes.rb
Rails.application.routes.draw do
  resources :actor_movies
  resources :movies
  resources :addresses
  resources :categories
  resources :actors
  resources :directors

  get '/persons/new', to: 'person#new'
  get '/persons', to: 'person#index'
  post '/persons/create', to: 'person#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/person_controller.rb
class PersonController < ApplicationController


  def index
    @actors = Actor.all
    @directors = Director.all
  end

  def new
  end

  def create
    if params[:type] == "Actor"
      @actor = Actor.create(first_name:params[:first_name], last_name:params[:last_name], birth_date:params[:birth_date], description:params[:description])
      respond_to do |format|
        if @actor.save
          format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
          format.json { render :show, status: :created, location: @actor }
        else
          format.html { render :new }
          format.json { render json: @actor.errors, status: :unprocessable_entity }
        end
      end
    else
      @director = Director.create(first_name:params[:first_name], last_name:params[:last_name], birth_date:params[:birth_date], description:params[:description])
      respond_to do |format|
        if @director.save
          format.html { redirect_to @director, notice: 'Director was successfully created.' }
          format.json { render :show, status: :created, location: @director }
        else
          format.html { render :new }
          format.json { render json: @director.errors, status: :unprocessable_entity }
        end
      end
    end

  end


end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/person/_form.html.erb
<%= form_tag(:persons => "/persons/create", :action => "create", :method => "post") do %>
  <h1>New Person!</h1>
<div>
  <%= label_tag :first_name %>
  <%= text_field_tag :first_name, params[:first_name] %>
</div>
<div>
  <%= label_tag :last_name %>
  <%= text_field_tag :last_name, params[:last_name] %>
</div>
<div>
  <%= label_tag :birth_date %>
  <%= date_field_tag :birth_date, params[:birth_date] %>
</div>
<div>
  <%= label_tag :description %>
  <%= text_field_tag :description, params[:description] %>
</div>
<div>
  <%= label_tag :director %>
  <%= radio_button_tag(:type, "Director", params[:type]) %>
  <%= label_tag :actor %>
  <%= radio_button_tag(:type, "Actor", params[:type]) %>
</div>
<div>
  <%= submit_tag "Submit" %>
</div>
<% end %>

app/views/person/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Persons</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth date</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.first_name %></td>
        <td><%= actor.last_name %></td>
        <td><%= actor.birth_date %></td>
        <td><%= actor.description %></td>
        <td>Actor</td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @directors.each do |director| %>
    <tr>
      <td><%= director.first_name %></td>
      <td><%= director.last_name %></td>
      <td><%= director.birth_date %></td>
      <td><%= director.description %></td>
      <td>Director</td>
      <td><%= link_to 'Show', director %></td>
      <td><%= link_to 'Edit', edit_director_path(director) %></td>
      <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', persons_new_path %>

app/views/person/new.html.erb
<%= render 'form', person: @person %>